import type { CortexManifest, TemporalData, ModuleNode } from '../types/index.js'
import { readFile, writeFile, cortexPath } from '../utils/files.js'
import { readManifest } from './manifest.js'
import { listModuleDocs } from './modules.js'
import { listDecisions } from './decisions.js'
import { classifyProject, getSizeLimits } from './project-size.js'

export interface ConstitutionData {
  modules?: ModuleNode[]
  entryPoints?: string[]
  externalDeps?: Record<string, string[]>
  temporal?: TemporalData | null
}

export async function generateConstitution(projectRoot: string, data?: ConstitutionData): Promise<string> {
  const manifest = await readManifest(projectRoot)
  const modules = await listModuleDocs(projectRoot)
  const decisions = await listDecisions(projectRoot)

  // Use passed-in data or read from disk (for small repos / standalone calls)
  let graphModules = data?.modules
  let entryPoints = data?.entryPoints
  let externalDeps = data?.externalDeps
  let temporal = data?.temporal ?? null

  if (!graphModules) {
    const graphContent = await readFile(cortexPath(projectRoot, 'graph.json'))
    if (graphContent) {
      try {
        const graph = JSON.parse(graphContent)
        graphModules = graph.modules
        entryPoints = graph.entryPoints
        externalDeps = graph.externalDeps
      } catch { /* graph too large to parse, skip */ }
    }
  }

  if (temporal === null && !data) {
    const temporalContent = await readFile(cortexPath(projectRoot, 'temporal.json'))
    if (temporalContent) {
      try { temporal = JSON.parse(temporalContent) as TemporalData } catch { /* skip */ }
    }
  }

  // Determine size-based limits for constitution content
  const size = manifest
    ? classifyProject(manifest.totalFiles, manifest.totalSymbols, manifest.totalModules)
    : (graphModules ? classifyProject(graphModules.length * 10, graphModules.reduce((s, m) => s + m.symbols, 0), graphModules.length) : 'medium' as const)
  const limits = getSizeLimits(size)

  const lines: string[] = [
    `# ${manifest?.project || 'Project'} — Constitution`,
    '',
    `> Auto-generated by CodeCortex. This is the AI's starting knowledge for this codebase.`,
    '',
  ]

  // Project overview
  if (manifest) {
    lines.push(
      `## Project`,
      `- **Name:** ${manifest.project}`,
      `- **Languages:** ${manifest.languages.join(', ')}`,
      `- **Files:** ${manifest.totalFiles}`,
      `- **Symbols:** ${manifest.totalSymbols}`,
      `- **Modules:** ${manifest.totalModules}`,
      `- **Last updated:** ${manifest.lastUpdated}`,
      '',
    )
  }

  // Architecture
  if (graphModules) {
    lines.push(`## Architecture`, '')

    if (entryPoints && entryPoints.length > 0) {
      lines.push(`**Entry points:** ${entryPoints.map(e => `\`${e}\``).join(', ')}`, '')
    }

    const modCap = limits.constitutionModules
    lines.push(`**Modules (${graphModules.length}):**`)
    const sorted = [...graphModules].sort((a, b) => b.lines - a.lines)
    const shown = sorted.slice(0, modCap)
    for (const mod of shown) {
      lines.push(`- **${mod.name}** (${mod.files.length} files, ${mod.lines} lines) — ${mod.language}`)
    }
    if (graphModules.length > modCap) {
      lines.push(`- ...and ${graphModules.length - modCap} more modules`)
    }
    lines.push('')

    // Key dependencies
    if (externalDeps) {
      const extDeps = Object.keys(externalDeps)
      if (extDeps.length > 0) {
        const depCap = limits.constitutionDeps
        const shownDeps = extDeps.slice(0, depCap)
        lines.push(`**External dependencies (${extDeps.length}):** ${shownDeps.map(d => `\`${d}\``).join(', ')}${extDeps.length > depCap ? `, ...and ${extDeps.length - depCap} more` : ''}`, '')
      }
    }
  }

  // Temporal signals
  if (temporal) {
    lines.push(`## Risk Map`, '')

    // Top hotspots
    const topHotspots = temporal.hotspots.slice(0, limits.constitutionHotspots)
    if (topHotspots.length > 0) {
      lines.push(`**Hottest files (most changes):**`)
      for (const h of topHotspots) {
        lines.push(`- \`${h.file}\` — ${h.changes} changes, ${h.stability.toUpperCase()}`)
      }
      lines.push('')
    }

    // Hidden couplings
    const hiddenCouplings = temporal.coupling.filter(c => !c.hasImport && c.strength >= 0.5)
    if (hiddenCouplings.length > 0) {
      lines.push(`**Hidden dependencies (co-change but no import):**`)
      for (const c of hiddenCouplings.slice(0, limits.constitutionCouplings)) {
        lines.push(`- \`${c.fileA}\` ↔ \`${c.fileB}\` — ${c.cochanges} co-changes (${Math.round(c.strength * 100)}%)`)
      }
      lines.push('')
    }

    // Bug-prone files
    const buggy = temporal.bugHistory.filter(b => b.fixCommits >= 2)
    if (buggy.length > 0) {
      lines.push(`**Bug-prone files:**`)
      for (const b of buggy.slice(0, limits.constitutionBugs)) {
        lines.push(`- \`${b.file}\` — ${b.fixCommits} fix commits`)
        for (const lesson of b.lessons.slice(0, limits.constitutionLessons)) {
          lines.push(`  - ${lesson}`)
        }
      }
      lines.push('')
    }
  }

  // Knowledge available
  lines.push(`## Available Knowledge`, '')
  if (modules.length > 0) {
    lines.push(`**Module docs:** ${modules.map(m => `\`${m}\``).join(', ')}`)
  }
  if (decisions.length > 0) {
    lines.push(`**Decision records:** ${decisions.length}`)
  }
  lines.push(
    ``,
    `Read \`.codecortex/modules/*.md\` directly for module deep-dives.`,
    `Use \`get_change_coupling\` before editing a file to check what else must change.`,
    `Use \`lookup_symbol\` to find any function, type, or class.`,
  )

  const content = lines.join('\n') + '\n'
  await writeFile(cortexPath(projectRoot, 'constitution.md'), content)
  return content
}
