import type { CortexManifest, DependencyGraph, TemporalData } from '../types/index.js'
import { readFile, writeFile, cortexPath } from '../utils/files.js'
import { readManifest } from './manifest.js'
import { readGraph } from './graph.js'
import { listModuleDocs } from './modules.js'
import { listDecisions } from './decisions.js'

export async function generateConstitution(projectRoot: string): Promise<string> {
  const manifest = await readManifest(projectRoot)
  const graph = await readGraph(projectRoot)
  const modules = await listModuleDocs(projectRoot)
  const decisions = await listDecisions(projectRoot)

  // Read temporal data
  let temporal: TemporalData | null = null
  const temporalContent = await readFile(cortexPath(projectRoot, 'temporal.json'))
  if (temporalContent) {
    temporal = JSON.parse(temporalContent) as TemporalData
  }

  const lines: string[] = [
    `# ${manifest?.project || 'Project'} — Constitution`,
    '',
    `> Auto-generated by CodeCortex. This is the AI's starting knowledge for this codebase.`,
    '',
  ]

  // Project overview
  if (manifest) {
    lines.push(
      `## Project`,
      `- **Name:** ${manifest.project}`,
      `- **Languages:** ${manifest.languages.join(', ')}`,
      `- **Files:** ${manifest.totalFiles}`,
      `- **Symbols:** ${manifest.totalSymbols}`,
      `- **Modules:** ${manifest.totalModules}`,
      `- **Last updated:** ${manifest.lastUpdated}`,
      '',
    )
  }

  // Architecture
  if (graph) {
    lines.push(`## Architecture`, '')

    if (graph.entryPoints.length > 0) {
      lines.push(`**Entry points:** ${graph.entryPoints.map(e => `\`${e}\``).join(', ')}`, '')
    }

    lines.push(`**Modules:**`)
    for (const mod of graph.modules) {
      lines.push(`- **${mod.name}** (${mod.files.length} files, ${mod.lines} lines) — ${mod.language}`)
    }
    lines.push('')

    // Key dependencies
    const extDeps = Object.keys(graph.externalDeps)
    if (extDeps.length > 0) {
      lines.push(`**External dependencies:** ${extDeps.map(d => `\`${d}\``).join(', ')}`, '')
    }
  }

  // Temporal signals
  if (temporal) {
    lines.push(`## Risk Map`, '')

    // Top hotspots
    const topHotspots = temporal.hotspots.slice(0, 5)
    if (topHotspots.length > 0) {
      lines.push(`**Hottest files (most changes):**`)
      for (const h of topHotspots) {
        lines.push(`- \`${h.file}\` — ${h.changes} changes, ${h.stability.toUpperCase()}`)
      }
      lines.push('')
    }

    // Hidden couplings
    const hiddenCouplings = temporal.coupling.filter(c => !c.hasImport && c.strength >= 0.5)
    if (hiddenCouplings.length > 0) {
      lines.push(`**Hidden dependencies (co-change but no import):**`)
      for (const c of hiddenCouplings.slice(0, 5)) {
        lines.push(`- \`${c.fileA}\` ↔ \`${c.fileB}\` — ${c.cochanges} co-changes (${Math.round(c.strength * 100)}%)`)
      }
      lines.push('')
    }

    // Bug-prone files
    const buggy = temporal.bugHistory.filter(b => b.fixCommits >= 2)
    if (buggy.length > 0) {
      lines.push(`**Bug-prone files:**`)
      for (const b of buggy.slice(0, 5)) {
        lines.push(`- \`${b.file}\` — ${b.fixCommits} fix commits`)
        for (const lesson of b.lessons.slice(0, 3)) {
          lines.push(`  - ${lesson}`)
        }
      }
      lines.push('')
    }
  }

  // Knowledge available
  lines.push(`## Available Knowledge`, '')
  if (modules.length > 0) {
    lines.push(`**Module docs:** ${modules.map(m => `\`${m}\``).join(', ')}`)
  }
  if (decisions.length > 0) {
    lines.push(`**Decision records:** ${decisions.length}`)
  }
  lines.push(
    ``,
    `Use \`get_module_context\` to deep-dive into any module.`,
    `Use \`get_change_coupling\` before editing a file to check what else must change.`,
    `Use \`lookup_symbol\` to find any function, type, or class.`,
  )

  const content = lines.join('\n') + '\n'
  await writeFile(cortexPath(projectRoot, 'constitution.md'), content)
  return content
}
