/**
 * Test fixture helpers.
 * Creates temporary .codecortex/ directories with known data for deterministic assertions.
 */

import { mkdtemp, rm, mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { tmpdir } from 'node:os'

export interface Fixture {
  root: string
  cleanup: () => Promise<void>
}

/** Create a temp directory with a minimal .codecortex/ knowledge store. */
export async function createFixture(): Promise<Fixture> {
  const root = await mkdtemp(join(tmpdir(), 'codecortex-test-'))
  const cortex = join(root, '.codecortex')

  await mkdir(cortex)
  await mkdir(join(cortex, 'modules'))
  await mkdir(join(cortex, 'decisions'))
  await mkdir(join(cortex, 'sessions'))

  // cortex.yaml
  await writeFile(join(cortex, 'cortex.yaml'), `version: 1.0.0
project: test-project
root: ${root}
generated: 2026-03-02T00:00:00.000Z
lastUpdated: 2026-03-02T00:00:00.000Z
languages:
  - typescript
  - python
totalFiles: 5
totalSymbols: 12
totalModules: 2
tiers:
  hot:
    - cortex.yaml
    - constitution.md
    - overview.md
    - graph.json
    - symbols.json
    - temporal.json
  warm:
    - modules/
  cold:
    - decisions/
    - sessions/
    - patterns.md
`)

  // constitution.md
  await writeFile(join(cortex, 'constitution.md'), `# test-project — Constitution

> Auto-generated by CodeCortex.

## Project
- **Name:** test-project
- **Languages:** typescript, python
- **Files:** 5
- **Symbols:** 12
- **Modules:** 2

## Architecture
**Entry points:** \`src/index.ts\`

**Modules:**
- **core** (3 files, 200 lines) — typescript
- **utils** (2 files, 100 lines) — typescript
`)

  // overview.md
  await writeFile(join(cortex, 'overview.md'), `# test-project — Overview

**Type:** node
**Languages:** typescript, python
**Files:** 5

## Entry Points
- \`src/index.ts\`

## Modules
- **core**
- **utils**
`)

  // symbols.json
  const symbols = {
    generated: '2026-03-02T00:00:00.000Z',
    total: 4,
    symbols: [
      { name: 'processData', kind: 'function', file: 'src/core/processor.ts', startLine: 5, endLine: 20, signature: 'export function processData(input: string): Result', exported: true },
      { name: 'Result', kind: 'interface', file: 'src/core/types.ts', startLine: 1, endLine: 8, signature: 'export interface Result', exported: true },
      { name: 'formatOutput', kind: 'function', file: 'src/utils/format.ts', startLine: 3, endLine: 10, signature: 'export function formatOutput(data: Result): string', exported: true },
      { name: 'TIMEOUT', kind: 'const', file: 'src/utils/config.ts', startLine: 1, endLine: 1, signature: 'const TIMEOUT = 5000', exported: false },
    ],
  }
  await writeFile(join(cortex, 'symbols.json'), JSON.stringify(symbols, null, 2))

  // graph.json
  const graph = {
    generated: '2026-03-02T00:00:00.000Z',
    modules: [
      { path: 'src/core', name: 'core', files: ['src/core/processor.ts', 'src/core/types.ts', 'src/core/index.ts'], language: 'typescript', lines: 200, symbols: 2 },
      { path: 'src/utils', name: 'utils', files: ['src/utils/format.ts', 'src/utils/config.ts'], language: 'typescript', lines: 100, symbols: 2 },
    ],
    imports: [
      { source: 'src/core/processor.ts', target: 'src/core/types.ts', specifiers: ['Result'] },
      { source: 'src/utils/format.ts', target: 'src/core/types.ts', specifiers: ['Result'] },
      { source: 'src/core/index.ts', target: 'src/core/processor.ts', specifiers: ['processData'] },
    ],
    calls: [
      { caller: 'src/core/processor.ts:processData', callee: 'formatOutput', file: 'src/core/processor.ts', line: 15 },
      { caller: 'src/utils/format.ts:formatOutput', callee: 'JSON.stringify', file: 'src/utils/format.ts', line: 7 },
    ],
    entryPoints: ['src/index.ts'],
    externalDeps: {
      'zod': ['src/core/processor.ts'],
      'node:path': ['src/utils/format.ts'],
    },
  }
  await writeFile(join(cortex, 'graph.json'), JSON.stringify(graph, null, 2))

  // temporal.json
  const temporal = {
    generated: '2026-03-02T00:00:00.000Z',
    periodDays: 90,
    totalCommits: 15,
    hotspots: [
      { file: 'src/core/processor.ts', changes: 8, stability: 'volatile', lastChanged: '2026-03-01T00:00:00.000Z', daysSinceChange: 1 },
      { file: 'src/utils/format.ts', changes: 3, stability: 'stable', lastChanged: '2026-02-15T00:00:00.000Z', daysSinceChange: 15 },
    ],
    coupling: [
      { fileA: 'src/core/processor.ts', fileB: 'src/core/types.ts', cochanges: 6, strength: 0.75, hasImport: true },
      { fileA: 'src/core/processor.ts', fileB: 'src/utils/format.ts', cochanges: 4, strength: 0.5, hasImport: false, warning: 'HIDDEN DEPENDENCY — 50% co-change rate' },
    ],
    bugHistory: [
      { file: 'src/core/processor.ts', fixCommits: 3, lessons: ['Race condition in async processing', 'Null check missing'] },
    ],
  }
  await writeFile(join(cortex, 'temporal.json'), JSON.stringify(temporal, null, 2))

  // patterns.md
  await writeFile(join(cortex, 'patterns.md'), `# Coding Patterns

No patterns recorded yet. Use \`update_patterns\` to add patterns.
`)

  return {
    root,
    cleanup: () => rm(root, { recursive: true, force: true }),
  }
}
